### PR TITLE
Add a beautiful background of a breaking wave.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
The image itself is owned by Carlin Ma Photography, not Triggr Health.
We have explicit written permission from the owner, Carlin Ma, to use
the photograph. We are NOT permitted to remove the watermark or use the
photograph externally (e.g., in marketing materials). Make the font
black so that text remains legible.

### CODE REVIEW

**Comment by joshgachnang** [comment]
Got a screenshot of it with the rest of the content on it? There's a lot of white in that picture..

**Comment by Kurt-von-Laven** [comment]
add background

I tried it out locally with and without additional blur. My personal preference was for the original, which is already mostly blurred, and that is what is in this pull request. I have never blurred an image before in my life though, so take it with a grain of salt.

**Comment by joshgachnang** [comment]
Oh I was thinking something like this: http://s3-us-west-2.amazonaws.com/i.cdpn.io/763.geFIK.4a084f36-42c1-48b8-ae8e-6dd2e5450632.png

**Comment by artdent** [comment]
The other way to preserve legibility is to make the image 50% transparent over a black background. (With an image editor, not with css.) Or to adjust whatever color slider gives you that effect...

**Comment by Kurt-von-Laven** [comment]
black font

Lazy man's solution: make font black. Let me know what you think.

**Comment by joshgachnang** [comment]
It looks alright with the black! Let's see it on the TV and go from there? Can you switch the color of the underline? Otherwise LGTM

**Comment by Kurt-von-Laven** [comment]
make underline black

Oops; good catch.

**Pull request merged**
